[project]
name = "tutorIA_docretrieval"
version = "1.0.0"
description = "API que armazena embeddings no redis e recupera textos"
dependencies = [
    "flask",
    "redis"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"